# Generated by Django 4.0.3 on 2022-05-18 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('slug', models.CharField(max_length=250)),
                ('discription', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, upload_to='car')),
                ('price', models.IntegerField()),
            ],
        ),
    ]
