# Generated by Django 4.0.3 on 2022-06-17 20:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('slug', models.CharField(max_length=250)),
                ('discription', models.TextField(blank=True)),
                ('main_image', models.ImageField(blank=True, upload_to='car')),
                ('price_1_2', models.CharField(blank=True, default='', max_length=250)),
                ('price_3_10', models.CharField(blank=True, default='', max_length=250)),
                ('price_11_20', models.CharField(blank=True, default='', max_length=250)),
                ('acceleration', models.FloatField(blank=True, null=True)),
                ('power', models.IntegerField(blank=True, null=True)),
                ('oil', models.CharField(blank=True, max_length=250, null=True)),
                ('wd', models.CharField(blank=True, max_length=250, null=True)),
                ('year', models.CharField(blank=True, max_length=250, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Car_secondary_img',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('image', models.ImageField(blank=True, upload_to='car')),
                ('N', models.IntegerField()),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.car')),
            ],
            options={
                'ordering': ('name',),
            },
        ),
    ]
