# Generated by Django 4.0.3 on 2022-05-24 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='acceleration',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='car',
            name='oil',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='car',
            name='power',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='car',
            name='wd',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='car',
            name='year',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
