# Generated by Django 4.0.3 on 2022-06-11 18:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_rename_image_car_main_image_car_secondary_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='car_secondary_img',
            name='added',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='car_secondary_img',
            name='image',
            field=models.ImageField(blank=True, upload_to='car'),
        ),
    ]
