# Generated by Django 4.0.3 on 2022-06-11 18:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_car_secondary_img_added_car_secondary_img_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='car_secondary_img',
            name='name',
            field=models.CharField(default=django.utils.timezone.now, max_length=250),
            preserve_default=False,
        ),
    ]
